# Generated by Django 3.2.8 on 2021-10-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_posts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='name',
        ),
    ]
